/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_server_NIOServer */

#ifndef _Included_demo_server_NIOServer
#define _Included_demo_server_NIOServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_server_NIOServer
 * Method:    socketServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_demo_server_NIOServer_socketServer
  (JNIEnv *, jclass);

/*
 * Class:     demo_server_NIOServer
 * Method:    socketClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_demo_server_NIOServer_socketClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
